# Fundamental Stock Data

This notebook offers a preview into how one can download free historical fundamentals for stocks across various sources. The data collected from these sources can be used to construct value and other fundamental strategies.

### Packages
This notebook will cover how one can download data using the <a href='https://pypi.org/project/simfin/' target="_blank" >simfin</a> and  <a href='https://pypi.org/project/yfinance/' target="_blank" >yfinance</a> packages. 

Note *Install them using "pip install simfin" and "pip install yfinance" if you have not done so*

In [1]:
import yfinance as yf 
import simfin as sf
import warnings
warnings.filterwarnings('ignore')

### Get Your SimFin API Key

- Step 1: Create an account at https://simfin.com. Confirm your account via email
- Step 2: Head over to https://simfin.com/data/api to obtain your api key


### Set Your SimFin Data Directory

Simfin requires you to set a data directory where simfin data will be downloaded. Downloaded data is used for faster retrieval in the future. The default location is a folder named simfin_data in the home directory.

In [2]:
api_key = "9378c297-d8d4-47f6-bc39-adbf8f41d589"
sf.config.set_api_key(api_key=api_key)

# set simfin_data
sf.set_data_dir('~/simfin_data/')

### Download historical financial data from simfin.
The three financial statements containing fundamental data are the quarterly income, balance sheet and cash flows statements. Data from these statements can be loaded for all us tickers from simfin as below.

In [3]:
income = sf.load_income(variant='quarterly', market='us')
balance_sheet = sf.load_balance(variant='quarterly', market='us')
cash_flow = sf.load_cashflow(variant='quarterly', market='us')

Dataset "us-income-quarterly" on disk (52 days old).
- Downloading ... 100.0%
- Extracting zip-file ... Done!
- Loading from disk ... Done!
Dataset "us-balance-quarterly" on disk (52 days old).
- Downloading ... 100.0%
- Extracting zip-file ... Done!
- Loading from disk ... Done!
Dataset "us-cashflow-quarterly" on disk (52 days old).
- Downloading ... 100.0%
- Extracting zip-file ... Done!
- Loading from disk ... Done!

All of the results obtained are multi-index dataframes where the row is (ticker,date) and the column is a financial statement item. One important columns for backtesting is the Publish Date. This is the date where the information was available to the public. 

For backtesting, we can assume the simfin data is available 1 business day after the Publish Date, since companies sometimes publish after market close or because we may not always be able to get the data immediately on publication for trading, depending on which data vendor you use. Since there are restatements to financial statements, even this will not be a fully "point-in-time" backtest where we only use information available at the time. It should be a reasonable approximation in many cases, however.

With that, let us observe the data for *cash flow*, *income* and *balance sheet* which are resourceful data when it comes to analysing the fundamental aspects of a company

In [4]:
cash_flow.head()

                    SimFinId Currency  Fiscal Year Fiscal Period Publish Date  \
Ticker Report Date
A      2020-04-30      45846      USD         2020            Q2   2020-06-01
       2020-07-31      45846      USD         2020            Q3   2020-09-01
       2020-10-31      45846      USD         2020            Q4   2020-12-18
       2021-01-31      45846      USD         2021            Q1   2021-03-02
       2021-04-30      45846      USD         2021            Q2   2021-06-01

                   Restated Date  Shares (Basic)  Shares (Diluted)  \
Ticker Report Date
A      2020-04-30     2021-03-02     309000000.0       312000000.0
       2020-07-31     2021-06-01     309000000.0       312000000.0
       2020-10-31     2021-09-01     308000000.0       311000000.0
       2021-01-31     2022-03-03     306000000.0       309000000.0
       2021-04-30     2022-03-03     306000000.0       306000000.0

                    Net Income/Starting Line  Depreciation & Amortization  \
Ticker Report Date
A      2020-04-30                101000000.0                   76000000.0
       2020-07-31                199000000.0                   77000000.0
       2020-10-31                222000000.0                   76000000.0
       2021-01-31                288000000.0                   76000000.0
       2021-04-30                216000000.0                   77000000.0

                    ...  Net Cash from Operating Activities  \
Ticker Report Date  ...
A      2020-04-30   ...                         313000000.0
       2020-07-31   ...                         290000000.0
       2020-10-31   ...                         377000000.0
       2021-01-31   ...                         238000000.0
       2021-04-30   ...                         472000000.0

                    Change in Fixed Assets & Intangibles  \
Ticker Report Date
A      2020-04-30                            -33000000.0
       2020-07-31                            -24000000.0
       2020-10-31                            -27000000.0
       2021-01-31                            -41000000.0
       2021-04-30                            -31000000.0

                    Net Change in Long Term Investment  \
Ticker Report Date
A      2020-04-30                                  NaN
       2020-07-31                                  NaN
       2020-10-31                                  NaN
       2021-01-31                                  NaN
       2021-04-30                                  NaN

                    Net Cash from Acquisitions & Divestitures  \
Ticker Report Date
A      2020-04-30                                         NaN
       2020-07-31                                         NaN
       2020-10-31                                         NaN
       2021-01-31                                         NaN
       2021-04-30                                -547000000.0

                    Net Cash from Investing Activities  Dividends Paid  \
Ticker Report Date
A      2020-04-30                          -53000000.0     -55000000.0
       2020-07-31                          -32000000.0     -56000000.0
       2020-10-31                          -27000000.0     -55000000.0
       2021-01-31                          -42000000.0     -59000000.0
       2021-04-30                         -587000000.0     -59000000.0

                    Cash from (Repayment of) Debt  \
Ticker Report Date
A      2020-04-30                      25000000.0
       2020-07-31                    -161000000.0
       2020-10-31                      35000000.0
       2021-01-31                     134000000.0
       2021-04-30                     427000000.0

                    Cash from (Repurchase of) Equity  \
Ticker Report Date
A      2020-04-30                       -126000000.0
       2020-07-31                         -9000000.0
       2020-10-31                       -246000000.0
       2021-01-31                       -319000000.0
       2021-04-30                       -194000000.0

                    Net Cash from Financing Activities  Net Change in Cash
Ticker Report Date
A      2020-04-30                         -156000000.0            97000000
       2020-07-31                         -231000000.0            35000000
       2020-10-31                         -269000000.0            83000000
       2021-01-31                         -316000000.0          -111000000
       2021-04-30                          166000000.0            51000000

[5 rows x 26 columns]

In [5]:
income.head()

                    SimFinId Currency  Fiscal Year Fiscal Period Publish Date  \
Ticker Report Date
A      2020-04-30      45846      USD         2020            Q2   2020-06-01
       2020-07-31      45846      USD         2020            Q3   2020-09-01
       2020-10-31      45846      USD         2020            Q4   2020-12-18
       2021-01-31      45846      USD         2021            Q1   2021-03-02
       2021-04-30      45846      USD         2021            Q2   2021-06-01

                   Restated Date  Shares (Basic)  Shares (Diluted)  \
Ticker Report Date
A      2020-04-30     2021-06-01     309000000.0       312000000.0
       2020-07-31     2021-09-01     309000000.0       312000000.0
       2020-10-31     2021-09-01     308000000.0       311000000.0
       2021-01-31     2022-03-03     306000000.0       309000000.0
       2021-04-30     2022-05-31     306000000.0       306000000.0

                         Revenue  Cost of Revenue  ...  \
Ticker Report Date                                 ...
A      2020-04-30   1.238000e+09     -581000000.0  ...
       2020-07-31   1.261000e+09     -592000000.0  ...
       2020-10-31   1.483000e+09     -695000000.0  ...
       2021-01-31   1.548000e+09     -710000000.0  ...
       2021-04-30   1.525000e+09     -708000000.0  ...

                    Non-Operating Income (Loss)  Interest Expense, Net  \
Ticker Report Date
A      2020-04-30                    19000000.0            -17000000.0
       2020-07-31                   -11000000.0            -18000000.0
       2020-10-31                   -16000000.0            -18000000.0
       2021-01-31                   -16000000.0            -19000000.0
       2021-04-30                   -15000000.0            -19000000.0

                    Pretax Income (Loss), Adj.  Abnormal Gains (Losses)  \
Ticker Report Date
A      2020-04-30                  121000000.0                      NaN
       2020-07-31                  219000000.0                      NaN
       2020-10-31                  283000000.0                      NaN
       2021-01-31                  312000000.0                      NaN
       2021-04-30                  273000000.0                      NaN

                    Pretax Income (Loss)  Income Tax (Expense) Benefit, Net  \
Ticker Report Date
A      2020-04-30              121000000                        -20000000.0
       2020-07-31              219000000                        -20000000.0
       2020-10-31              283000000                        -61000000.0
       2021-01-31              312000000                        -24000000.0
       2021-04-30              273000000                        -57000000.0

                    Income (Loss) from Continuing Operations  \
Ticker Report Date
A      2020-04-30                                  101000000
       2020-07-31                                  199000000
       2020-10-31                                  222000000
       2021-01-31                                  288000000
       2021-04-30                                  216000000

                    Net Extraordinary Gains (Losses)  Net Income  \
Ticker Report Date
A      2020-04-30                                NaN   101000000
       2020-07-31                                NaN   199000000
       2020-10-31                                NaN   222000000
       2021-01-31                                NaN   288000000
       2021-04-30                                NaN   216000000

                    Net Income (Common)
Ticker Report Date
A      2020-04-30             101000000
       2020-07-31             199000000
       2020-10-31             222000000
       2021-01-31             288000000
       2021-04-30             216000000

[5 rows x 26 columns]

In [6]:
balance_sheet.head()

                    SimFinId Currency  Fiscal Year Fiscal Period Publish Date  \
Ticker Report Date
A      2020-04-30      45846      USD         2020            Q2   2020-06-01
       2020-07-31      45846      USD         2020            Q3   2020-09-01
       2020-10-31      45846      USD         2020            Q4   2020-12-18
       2021-01-31      45846      USD         2021            Q1   2021-03-02
       2021-04-30      45846      USD         2021            Q2   2021-06-01

                   Restated Date  Shares (Basic)  Shares (Diluted)  \
Ticker Report Date
A      2020-04-30     2020-06-01     309000000.0       312000000.0
       2020-07-31     2020-09-01     309000000.0       312000000.0
       2020-10-31     2021-12-17     308000000.0       311000000.0
       2021-01-31     2021-03-02     306000000.0       309000000.0
       2021-04-30     2021-06-01     306000000.0       306000000.0

                    Cash, Cash Equivalents & Short Term Investments  \
Ticker Report Date
A      2020-04-30                                      1.324000e+09
       2020-07-31                                      1.358000e+09
       2020-10-31                                      1.441000e+09
       2021-01-31                                      1.329000e+09
       2021-04-30                                      1.380000e+09

                    Accounts & Notes Receivable  ...  Short Term Debt  \
Ticker Report Date                               ...
A      2020-04-30                  8.860000e+08  ...      700000000.0
       2020-07-31                  9.300000e+08  ...       40000000.0
       2020-10-31                  1.038000e+09  ...       75000000.0
       2021-01-31                  1.087000e+09  ...      314000000.0
       2021-04-30                  1.075000e+09  ...      205000000.0

                    Total Current Liabilities  Long Term Debt  \
Ticker Report Date
A      2020-04-30                1.945000e+09    1.788000e+09
       2020-07-31                1.314000e+09    2.283000e+09
       2020-10-31                1.467000e+09    2.284000e+09
       2021-01-31                1.687000e+09    2.185000e+09
       2021-04-30                1.758000e+09    2.727000e+09

                    Total Noncurrent Liabilities  Total Liabilities  \
Ticker Report Date
A      2020-04-30                   2.742000e+09       4.687000e+09
       2020-07-31                   3.251000e+09       4.565000e+09
       2020-10-31                   3.287000e+09       4.754000e+09
       2021-01-31                   3.183000e+09       4.870000e+09
       2021-04-30                   3.830000e+09       5.588000e+09

                    Share Capital & Additional Paid-In Capital  \
Ticker Report Date
A      2020-04-30                                 5.291000e+09
       2020-07-31                                 5.327000e+09
       2020-10-31                                 5.314000e+09
       2021-01-31                                 5.269000e+09
       2021-04-30                                 5.274000e+09

                    Treasury Stock  Retained Earnings  Total Equity  \
Ticker Report Date
A      2020-04-30              NaN         15000000.0  4.768000e+09
       2020-07-31              NaN        130000000.0  4.981000e+09
       2020-10-31              NaN         81000000.0  4.873000e+09
       2021-01-31              NaN          4000000.0  4.804000e+09
       2021-04-30              NaN        -12000000.0  4.810000e+09

                    Total Liabilities & Equity
Ticker Report Date
A      2020-04-30                   9455000000
       2020-07-31                   9546000000
       2020-10-31                   9627000000
       2021-01-31                   9674000000
       2021-04-30                  10398000000

[5 rows x 28 columns]

With that, let us observe how many tickers are available for each statement, including the start and end dates for each of our statement

In [7]:
def describe_data(data, data_name):
  size = len(set(data.index.get_level_values(0)))
  start_dt = data.index.get_level_values(1).min().strftime('%Y%m%d')
  end_dt = data.index.get_level_values(1).max().strftime('%Y%m%d')
  print (f'{data_name}: {size} tickers. Date range: {start_dt} to {end_dt}')

describe_data(income ,'Income Data')
describe_data(balance_sheet ,'Balance Sheet Data')
describe_data(cash_flow ,'Cash Flow Data')

Income Data: 3626 tickers. Date range: 20200430 to 20250228
Balance Sheet Data: 3629 tickers. Date range: 20200430 to 20250228
Cash Flow Data: 3629 tickers. Date range: 20200430 to 20250228

If you notice above, the simfin data ends a year ago. They only have 1 year lagged data. To get the most recent financial statement information, you can use yahoo finance. First you must obtain a yfinance.Ticker object for your desired ticker.

In [8]:
yf_ticker = yf.Ticker('AAPL')

# Get the quarterly cash flow statements from yfinance
income_yf = yf_ticker.quarterly_financials
cash_flow_yf = yf_ticker.quarterly_cashflow
balance_sheet = yf_ticker.quarterly_balance_sheet

In [9]:
income_yf.head()

,2025-12-31,2025-09-30,2025-06-30,2025-03-31,2024-12-31
Tax Effect Of Unusual Items,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Tax Rate For Calcs,1.750000e-01,1.627240e-01,1.640000e-01,1.550000e-01,1.470000e-01
Normalized EBITDA,5.406600e+10,3.555400e+10,3.103200e+10,3.225000e+10,4.591200e+10
Net Income From Continuing Operation Net Minority Interest,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10
Reconciled Depreciation,3.214000e+09,3.127000e+09,2.830000e+09,2.661000e+09,3.080000e+09

In [10]:
cash_flow_yf.head()

,2025-12-31,2025-09-30,2025-06-30,2025-03-31,2024-12-31,2024-09-30,2024-06-30
Free Cash Flow,5.155200e+10,2.648600e+10,2.440500e+10,2.088100e+10,2.699500e+10,NaN,NaN
Repurchase Of Capital Stock,-2.470100e+10,-2.013200e+10,-2.107500e+10,-2.589800e+10,-2.360600e+10,NaN,NaN
Repayment Of Debt,-8.074000e+09,-1.185000e+09,-1.770000e+09,9.760000e+08,-8.953000e+09,NaN,NaN
Issuance Of Debt,NaN,0.000000e+00,NaN,NaN,NaN,0.0,NaN
Capital Expenditure,-2.373000e+09,-3.242000e+09,-3.462000e+09,-3.071000e+09,-2.940000e+09,NaN,NaN

In [11]:
balance_sheet.head()

,2025-12-31,2025-09-30,2025-06-30,2025-03-31,2024-12-31,2024-09-30
Ordinary Shares Number,1.469793e+10,1.477326e+10,1.485672e+10,1.493932e+10,1.503787e+10,NaN
Share Issued,1.469793e+10,1.477326e+10,1.485672e+10,1.493932e+10,1.503787e+10,NaN
Net Debt,4.519200e+10,6.272300e+10,6.542900e+10,7.002400e+10,6.650000e+10,NaN
Total Debt,9.050900e+10,9.865700e+10,1.016980e+11,9.818600e+10,9.679900e+10,NaN
Tangible Book Value,8.819000e+10,7.373300e+10,6.583000e+10,6.679600e+10,6.675800e+10,NaN

As the data providers are from two completely different sources, extra care and caution must be taken when it comes to merging and integrating financial data of one company from various sources in order to get the full/complete range of data.

### Downloading historical financial data from YahooFinance

yfinance is a free, popular, and easy-to-use library that pulls data from Yahoo Finance (no API key required). It works well for stocks, ETFs, indices, cryptocurrencies, forex, etc.

In [17]:
# Download a sample of 10 tickers historical Market Data (Prices, Volume, Dividends, Splits)
tickers = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META', 'TSLA', 'NVDA', 'JPM', 'V', 'DIS']
start_date = '2020-01-01'
end_date = '2023-12-31'

price_data = yf.download(tickers, start=start_date, end=end_date)
print("Columns in the downloaded price data:", set(list(it[0] for it in price_data.columns)))
price_data.head()

[*********************100%***********************]  10 of 10 completed

Columns in the downloaded price data: {'Low', 'Volume', 'Close', 'High', 'Open'}

Price           Close                                                \
Ticker           AAPL       AMZN         DIS      GOOGL         JPM
Date
2020-01-02  72.400520  94.900497  144.790268  67.873024  119.036392
2020-01-03  71.696640  93.748497  143.129395  67.517952  117.465553
2020-01-06  72.267921  95.143997  142.298935  69.317581  117.372169
2020-01-07  71.928047  95.343002  142.347794  69.183708  115.376770
2020-01-08  73.085114  94.598503  142.054703  69.676117  116.276833

Price                                                                ...  \
Ticker            META        MSFT      NVDA       TSLA           V  ...
Date                                                                 ...
2020-01-02  208.324783  152.158401  5.971076  28.684000  182.809280  ...
2020-01-03  207.222488  150.263779  5.875505  29.534000  181.355377  ...
2020-01-06  211.125229  150.652161  5.900146  30.102667  180.963181  ...
2020-01-07  211.582031  149.278549  5.971575  31.270666  180.484955  ...
2020-01-08  213.727051  151.656342  5.982776  32.809334  183.574463  ...

Price          Volume                                                   \
Ticker           AAPL      AMZN      DIS     GOOGL       JPM      META
Date
2020-01-02  135480400  80580000  9502100  27278000  10803700  12077100
2020-01-03  146322800  75288000  7320200  23408000  10386800  11188400
2020-01-06  118387200  81236000  8262500  46768000  10259000  17058900
2020-01-07  108872000  80898000  6906500  34330000  10531300  14912400
2020-01-08  132079200  70160000  6984200  35314000   9695300  13475000

Price
Ticker          MSFT       NVDA       TSLA         V
Date
2020-01-02  22622100  237536000  142981500   8733000
2020-01-03  21116200  205384000  266677500   4899700
2020-01-06  20813700  262636000  151995000  10109500
2020-01-07  21634100  314856000  268231500   4392300
2020-01-08  27746500  277108000  467164500   5712000

[5 rows x 50 columns]

### Downloading Financial Statements (Fundamentals)

In [18]:
stock = yf.Ticker("AAPL")   # or "MSFT", "META", "TSLA", etc.

# Income Statement (Profit & Loss)
income_stmt = stock.financials          # annual
income_quarterly = stock.quarterly_financials

# Balance Sheet
balance_sheet = stock.balance_sheet
balance_quarterly = stock.quarterly_balance_sheet

# Cash Flow Statement
cashflow = stock.cashflow
cashflow_quarterly = stock.quarterly_cashflow

# Example: show last 3 years of net income
print(income_stmt.loc["Net Income"].head(3))

# Many other useful attributes
print(stock.info)               # dictionary with 100+ fields (marketCap, trailingPE, beta, sector, etc.)
print(stock.major_holders)
print(stock.institutional_holders)
print(stock.recommendations_summary)   # analyst ratings
print(stock.earnings_dates)
print(stock.dividends)          # dividend history
print(stock.splits)

2025-09-30    1.120100e+11
2024-09-30    9.373600e+10
2023-09-30    9.699500e+10
Name: Net Income, dtype: float64
{'address1': 'One Apple Park Way', 'city': 'Cupertino', 'state': 'CA', 'zip': '95014', 'country': 'United States', 'phone': '(408) 996-1010', 'website': 'https://www.apple.com', 'industry': 'Consumer Electronics', 'industryKey': 'consumer-electronics', 'industryDisp': 'Consumer Electronics', 'sector': 'Technology', 'sectorKey': 'technology', 'sectorDisp': 'Technology', 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers exclusive original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.', 'fullTimeEmployees': 150000, 'companyOfficers': [{'maxAge': 1, 'name': 'Mr. Timothy D. Cook', 'age': 64, 'title': 'CEO & Director', 'yearBorn': 1961, 'fiscalYear': 2025, 'totalPay': 16759518, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Kevan  Parekh', 'age': 53, 'title': 'Senior VP & CFO', 'yearBorn': 1972, 'fiscalYear': 2025, 'totalPay': 4034174, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Sabih  Khan', 'age': 58, 'title': 'Senior VP & Chief Operating Officer', 'yearBorn': 1967, 'fiscalYear': 2025, 'totalPay': 5021905, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': "Ms. Deirdre  O'Brien", 'age': 58, 'title': 'Senior Vice President of Retail & People', 'yearBorn': 1967, 'fiscalYear': 2025, 'totalPay': 5037867, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Katherine L. Adams', 'age': 61, 'title': 'Senior VP & Secretary', 'yearBorn': 1964, 'fiscalYear': 2025, 'totalPay': 5022482, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Ben  Borders', 'age': 44, 'title': 'Principal Accounting Officer', 'yearBorn': 1981, 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Suhasini  Chandramouli', 'title': 'Director of Investor Relations', 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Jennifer G. Newstead J.D.', 'age': 54, 'title': 'Senior VP & General Counsel', 'yearBorn': 1971, 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Kristin Huguet Quayle', 'title': 'Vice President of Worldwide Communications', 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Greg  Joswiak', 'title': 'Senior Vice President of Worldwide Marketing', 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}], 'auditRisk': 2, 'boardRisk': 1, 'compensationRisk': 7, 'shareHolderRightsRisk': 1, 'overallRisk': 1, 'governanceEpochDate': 1772323200, 'compensationAsOfEpochDate': 1767139200, 'irWebsite': 'http://investor.apple.com/', 'executiveTeam': [], 'maxAge': 86400, 'priceHint': 2, 'previousClose': 259.88, 'open': 257.695, 'dayLow': 256.95, 'dayHigh': 261.78, 'regularMarketPreviousClose': 259.88, 'regularMarketOpen': 257.695, 'regularMarketDayLow': 256.95, 'regularMarketDayHigh': 261.78, 'dividendRate': 1.04, 'dividendYield': 0.4, 'exDividendDate': 1770595200, 'payoutRatio': 0.1304, 'fiveYearAvgDividendYield': 0.52, 'beta': 1.116, 'trailingPE': 33.103794, 'forwardPE': 28.14373, 'volume': 7900058, 'regularMarketVolume': 7900058, 'averageVolume': 48544150, 'averageVolume10days': 43457250, 'averageDailyVolume10Day': 43457250, 'bid': 261.37, 'ask': 262.98, 'bidSize': 1, 'askSize': 4, 'marketCap': 3843801219072, 'nonDilutedMarketCap': 3815334663200, 'fiftyTwoWeekLow': 169.21, 'fiftyTwoWeekHigh': 288.62, 'allTimeHigh': 288.62, 'allTimeLow': 0.049107, 'priceToSalesTrailing12Months': 8.823809, 'fiftyDayAverage': 264.0382, 'twoHundredDayAverage': 244.44135, 'trailingAnnualDividendRate': 1.03, 'trailingAnnualDividendYield': 0.0039633675, 'currency': 'USD', 'tradeable': False, 'enterpriseValue': 3838936612864, 'profitMargins': 0.27037, 'floatShares': 14656182062, 'sharesOutstanding': 14681140000, 'sharesShort': 133373267, 'sharesShortPriorMonth': 113576032, 'sharesShortPreviousMonthDate': 1768435200, 'dateShortInterest': 1770940800, 'sharesPercentSharesOut': 0.0091, 'heldPercentInsiders': 0.01637, 'heldPercentInstitutions': 0.65212, 'shortRatio': 2.32, 'shortPercentOfFloat': 0.0091, 'impliedSharesOutstanding': 14697926000, 'bookValue': 5.998, 'priceToBook': 43.601196, 'lastFiscalYearEnd': 1758931200, 'nextFiscalYearEnd': 1790467200, 'mostRecentQuarter': 1766793600, 'earningsQuarterlyGrowth': 0.159, 'netIncomeToCommon': 117776998400, 'trailingEps': 7.9, 'forwardEps': 9.2923, 'lastSplitFactor': '4:1', 'lastSplitDate': 1598832000, 'enterpriseToRevenue': 8.813, 'enterpriseToEbitda': 25.107, '52WeekChange': 0.17677963, 'SandP52WeekChange': 0.21965265, 'lastDividendValue': 0.26, 'lastDividendDate': 1770595200, 'quoteType': 'EQUITY', 'currentPrice': 261.52, 'targetHighPrice': 350.0, 'targetLowPrice': 205.0, 'targetMeanPrice': 295.43536, 'targetMedianPrice': 300.0, 'recommendationMean': 1.89583, 'recommendationKey': 'buy', 'numberOfAnalystOpinions': 41, 'totalCash': 66907000832, 'totalCashPerShare': 4.557, 'ebitda': 152901992448, 'totalDebt': 90509000704, 'quickRatio': 0.845, 'currentRatio': 0.974, 'totalRevenue': 435617005568, 'debtToEquity': 102.63, 'revenuePerShare': 29.305, 'returnOnAssets': 0.24377, 'returnOnEquity': 1.5202099, 'grossProfits': 206157004800, 'freeCashflow': 106312753152, 'operatingCashflow': 135471996928, 'earningsGrowth': 0.183, 'revenueGrowth': 0.157, 'grossMargins': 0.47325, 'ebitdaMargins': 0.35099998, 'operatingMargins': 0.35374, 'financialCurrency': 'USD', 'symbol': 'AAPL', 'language': 'en-US', 'region': 'US', 'typeDisp': 'Equity', 'triggerable': True, 'customPriceAlertConfidence': 'HIGH', 'longName': 'Apple Inc.', 'corporateActions': [], 'regularMarketTime': 1773155828, 'exchange': 'NMS', 'messageBoardId': 'finmb_24937', 'exchangeTimezoneName': 'America/New_York', 'exchangeTimezoneShortName': 'EDT', 'gmtOffSetMilliseconds': -14400000, 'market': 'us_market', 'esgPopulated': False, 'marketState': 'REGULAR', 'regularMarketChangePercent': 0.63105434, 'regularMarketPrice': 261.52, 'shortName': 'Apple Inc.', 'cryptoTradeable': False, 'hasPrePostMarketData': True, 'firstTradeDateMilliseconds': 345479400000, 'regularMarketChange': 1.6399841, 'regularMarketDayRange': '256.95 - 261.78', 'fullExchangeName': 'NasdaqGS', 'averageDailyVolume3Month': 48544150, 'fiftyTwoWeekLowChange': 92.30998, 'fiftyTwoWeekLowChangePercent': 0.545535, 'fiftyTwoWeekRange': '169.21 - 288.62', 'fiftyTwoWeekHighChange': -27.100006, 'fiftyTwoWeekHighChangePercent': -0.09389511, 'fiftyTwoWeekChangePercent': 17.677963, 'dividendDate': 1770854400, 'earningsTimestamp': 1769720400, 'earningsTimestampStart': 1777579200, 'earningsTimestampEnd': 1777579200, 'earningsCallTimestampStart': 1769724000, 'earningsCallTimestampEnd': 1769724000, 'isEarningsDateEstimate': True, 'epsTrailingTwelveMonths': 7.9, 'epsForward': 9.2923, 'epsCurrentYear': 8.49919, 'priceEpsCurrentYear': 30.769989, 'fiftyDayAverageChange': -2.518219, 'fiftyDayAverageChangePercent': -0.009537328, 'twoHundredDayAverageChange': 17.078644, 'twoHundredDayAverageChangePercent': 0.069868065, 'sourceInterval': 15, 'exchangeDataDelayedBy': 0, 'averageAnalystRating': '1.9 - Buy', 'displayName': 'Apple', 'trailingPegRatio': 2.3261}
Breakdown                          Value
insidersPercentHeld              0.01637
institutionsPercentHeld          0.65212
institutionsFloatPercentHeld     0.66298
institutionsCount             7520.00000
  Date Reported                         Holder  pctHeld      Shares  \
0    2025-12-31             Vanguard Group Inc   0.0972  1426283914
1    2025-12-31                 Blackrock Inc.   0.0786  1154665731
2    2025-12-31       State Street Corporation   0.0411   604056505
3    2025-12-31  Geode Capital Management, LLC   0.0244   358032517
4    2025-12-31                       FMR, LLC   0.0209   307397264
5    2025-12-31                 Morgan Stanley   0.0157   230483035
6    2025-12-31        Berkshire Hathaway, Inc   0.0155   227917808
7    2025-12-31            JPMORGAN CHASE & CO   0.0154   225419111
8    2025-12-31  Price (T.Rowe) Associates Inc   0.0139   203499482
9    2025-12-31                    NORGES BANK   0.0131   192255086

          Value  pctChange
0  373001753519     0.0192
1  301968169285     0.0073
2  157972850551     0.0110
3   93632659912     0.0052
4   80390529104     0.0137
5   60275920781     0.0060
6   59605062644    -0.0432
7   58951603432    -0.5237
8   53219182296    -0.0435
9   50278547978     0.0129
  period  strongBuy  buy  hold  sell  strongSell
0     0m          6   25    15     1           1
1    -1m          5   25    16     1           1
2    -2m          6   24    15     1           2
3    -3m          5   24    15     1           3
                           EPS Estimate  Reported EPS  Surprise(%) Event Type
Earnings Date
2025-05-01 16:30:00-04:00          1.63          1.65         1.41   Earnings
2025-02-27 12:00:00-05:00           NaN           NaN          NaN    Meeting
2025-01-30 16:31:00-05:00          2.35          2.40         2.15   Earnings
2024-10-31 16:31:00-04:00          1.60          1.64         2.35   Earnings
2024-08-01 16:30:00-04:00          1.35          1.40         3.99   Earnings
2024-05-02 16:31:00-04:00          1.50          1.53         1.97   Earnings
2024-02-01 16:00:00-05:00          2.10          2.18         3.90   Earnings
2023-11-02 16:30:00-04:00          1.39          1.46         4.92   Earnings
2023-08-03 16:30:00-04:00          1.19          1.26         5.49   Earnings
2023-05-04 16:30:00-04:00          1.43          1.52         6.03   Earnings
2023-02-02 16:30:00-05:00          1.94          1.88        -2.88   Earnings
2022-10-27 16:30:00-04:00          1.27          1.29         1.55   Earnings
Date
1987-05-11 00:00:00-04:00    0.000536
1987-08-10 00:00:00-04:00    0.000536
1987-11-17 00:00:00-05:00    0.000714
1988-02-12 00:00:00-05:00    0.000714
1988-05-16 00:00:00-04:00    0.000714
                               ...
2025-02-10 00:00:00-05:00    0.250000
2025-05-12 00:00:00-04:00    0.260000
2025-08-11 00:00:00-04:00    0.260000
2025-11-10 00:00:00-05:00    0.260000
2026-02-09 00:00:00-05:00    0.260000
Name: Dividends, Length: 90, dtype: float64
Date
1987-06-16 00:00:00-04:00    2.0
2000-06-21 00:00:00-04:00    2.0
2005-02-28 00:00:00-05:00    2.0
2014-06-09 00:00:00-04:00    7.0
2020-08-31 00:00:00-04:00    4.0
Name: Stock Splits, dtype: float64